CREATE TABLE AUTHOR
(
	AUTHOR_ID 	   BIGINT NOT NULL,
	AUTHOR_CODE     VARCHAR(80) NOT NULL UNIQUE,
	NAME       	     VARCHAR(80) NOT NULL,
	MIDDLENAME 	     VARCHAR(80) NOT NULL,
	LASTNAME   	     VARCHAR(80) NOT NULL,
	PRIMARY KEY(AUTHOR_ID)
);
